### ISSUE TITLE
Results on the UEA multivariate archive?

### ISSUE THREAD

**Issue by fpetitjean** [hfawaz/dl-4-tsc#23]
Hi Hassan, 
Do you have, by any chance, the results of ResNet on https://arxiv.org/abs/1811.00075? 
Just wondering :)
François

**Comment by hfawaz** [comment]
Hi François,
In fact I have shared them with Angus a while ago. 
The problem is that some datasets contained some undocumented NaN values which deteriorated  the accuracy of ResNet / Inception.  
I can send you the results if you want, but I believe I should re-run them on a corrected version of the archive. 
Cheers,

**Comment by fpetitjean** [comment]
Ok, let's see if some of us get to rerunning them one day!

**Comment by guozhong-li** [comment]
> Hi François,
> In fact I have shared them with Angus a while ago.
> The problem is that some datasets contained some undocumented NaN values which deteriorated the accuracy of ResNet / Inception.
> I can send you the results if you want, but I believe I should re-run them on a corrected version of the archive.
> Cheers,

Hi, can you share the results with UEA datasets, 

thanks
