### ISSUE TITLE
can't reproduce the results with FordB dataset

### ISSUE THREAD

**Issue by jorgemarcoes** [hfawaz/dl-4-tsc#29]
Hi there,

congratulations for this amazing repository!

I'm trying to reproduce some of the results, but I was going crazy with the FordB dataset because I was obtaining a much lower accuracy with every model. Then I checked the results in the file: "dl-4-tsc/results/results-ucr-128.csv" (below a sample of that file)
![Captura de pantalla 2020-06-26 a las 10 14 11](https://user-images.githubusercontent.com/47383962/85835712-d16fda00-b795-11ea-9f1b-8f6ab87d8e32.png)

They don't match with the results table, where you get 87.8 accuracy with the FCN model as instance in stead of 77.x that is shown in the results file.

Is that all right? Am I missing something?

Thanks in advance,
Jorge

**Comment by hfawaz** [comment]
Thanks for your interest in this project.
Indeed there is a difference. 
In fact the results in the table come from an old version of the datasets. 
Since you are using the [128 UCR archive 2018](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/), you should refer to the [following table](https://github.com/hfawaz/dl-4-tsc/blob/master/results/results-ucr-128.csv) where FCN achieves similar results to yours. 
Hope this helps.

**Comment by jorgemarcoes** [comment]
Ok, thanks, that helps! Please consider mention in the project description that there is a difference between the paper results and the current results with the newest datasets. That may help other people trying to reproduce / improve the results.

Best, Jorge
