### ISSUE TITLE
How do you load the MTS archive for Multivariate

### ISSUE THREAD

**Issue by sabooakhter** [hfawaz/dl-4-tsc#35]
Hey Hassan,
AsSalaamu Alaykum, can you explain to me how you formatted the MTS archive set to be ingested by your scripts? When I download it, it's in the form of a matlab file and I don't have matlab to extract the data. Please advise. Thanks,

Sincerely,
Sohaib

**Comment by sabooakhter** [comment]
I got it working, looked at one of your earlier posts where you stated you should use the transform_mts_to_ucr_format() function

**Comment by cedced19** [comment]
@sabooakhter where did you get the MTS archive ? The link is broken, and I can find it in any other place.

**Comment by perrys21** [comment]
@cedced19 hello friend, did you manage to find the MTS archive? I am also in the search for it.

**Comment by hadifawaz1999** [comment]
Hello everyone, 

In order to load the mts datasets, it is now possible to do it with [aeon](https://www.aeon-toolkit.org/en/stable/) (a python package for time series machine learning) as such:

```
from aeon.datasets import load_classification

dataset_name = "Libras"
xtrain, ytrain = load_classification(dataset_name, split="train")
```

You can also find all the models form this repository implemented in aeon as well in aeon.classification.deep_learning
