### ISSUE TITLE
Miss MTS dataset

### ISSUE THREAD

**Issue by yuhengguo** [hfawaz/dl-4-tsc#52]
Thanks for the code, maybe it has been a long time now and the MTS link is invalid. 
Would you please provide an alternative link for the dataset?

Thank you so much and have a great day.

**Comment by zhaosheng-thu** [comment]
Same request, thank u so much!

**Comment by hadifawaz1999** [comment]
@yuhengguo @zhaosheng-thu for the MTS, or any Time Series Classification dataset they can now be loaded from the [aeon-toolkit](https://github.com/aeon-toolkit/aeon) by the following:

```
from aeon.datasets import load_classification

dataset_name = "Libras"
xtrain, ytrain, meta_train = load_classification(dataset_name, split="train")
```

of course since the dl4tsc paper was published, much more data has been released, you can check all of them on [tsc.com/datasets](http://timeseriesclassification.com/dataset.php), you choose the dataset name and load it as explained above using `aeon`

let me know if anything more is needed.

**Comment by TonyBagnall** [comment]
you can also load the regression and forecasting and regression archive data :)
